config:
  database:
    host: "0.0.0.0"
    port: "5439"
    user: "postgres"
    dbname: "postgres"
  parking-lot:
    max-occupancy: 5
    starting-rate: 3.0
    three-hour-mod: 1.5
    six-hour-mod: 2.25
    all-day-mod: 3.375